name: SolaceMobileIOS
options:
  bundleIdPrefix: dev.yvictor
  deploymentTarget:
    iOS: "16.0"
packages:
  SolaceMobileSwift:
    path: ../swift
targets:
  SolaceMobileIOS:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - Sources
    dependencies:
      - package: SolaceMobileSwift
        product: SolaceKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.yvictor.SolaceMobileIOS
        PRODUCT_NAME: SolaceMobileIOS
        INFOPLIST_FILE: Sources/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_VERSION: "6.0"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
      configs:
        Debug:
          ONLY_ACTIVE_ARCH: YES
          ARCHS[sdk=iphonesimulator*]: x86_64
        Release:
          ONLY_ACTIVE_ARCH: YES
          ARCHS[sdk=iphonesimulator*]: x86_64
